### ISSUE TITLE
Bot is not working 

### ISSUE THREAD

**Issue by Tjoosten** [fat/haunt#17]
@fat can you please help me or is a issue in the package?
![schermafbeelding 2015-04-21 om 21 48 41](https://cloud.githubusercontent.com/assets/5157609/7261235/5941ab70-e870-11e4-87f7-d761c7010aff.png)

**Comment by parkr** [comment]
@Tjoosten You must write a file called `.issue_guidelines.js` – it is trying to load a file that isn't there. If you want some ideas, see the [examples directory](https://github.com/fat/haunt/tree/master/examples).
