### ISSUE TITLE
readme augment

### ISSUE THREAD

**Issue by paulirish** [fat/haunt#3]
can you link to where the bot has interacted on a public repo?  
also can you share the entirety of some of the rules you've written? 
that'd help a lot !

**Comment by fat** [comment]
Sure thing - added this to the readme: https://github.com/fat/haunt/commit/c05cbf8a4d1c214e3db1044e6fb4d75975abbe41 is this what you had in mind?

**Comment by paulirish** [comment]
perfecto.  thank you sir.
